spring:
  application.name: security
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:5173/callback/
            scope: [ 'openid', 'profile', 'email' ]
        provider:
          auth0:
            issuer-uri:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
using:
  spring:
    schedulerFactory: false
logging:
  level:
    org:
      springframework:
        security: TRACE
jwt:
  secret:
