spring:
  application.name: security
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: WnpeY34fx99lDR9QqXb7VrXe9tCvmg1h
            client-secret: LI9u6F-qIy9Pj9oH9HJz1eGtP_XPN4-iDSPApL6H5GkoKCj0aesZRn6WhftB-Qv_
            authorization-grant-type: authorization_code
            #            For Frontend
            #            redirect-uri: http://localhost:3000/callback
            #            For Backend
            redirect-uri: http://localhost:5173/callback/
            scope: [ 'openid', 'profile', 'email' ]
        provider:
          auth0:
            issuer-uri: https://dev-5h6eu6edsmldpqe6.us.auth0.com/
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
using:
  spring:
    schedulerFactory: false
logging:
  level:
    org:
      springframework:
        security: TRACE
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
